import Link from 'next/link'
import Head from 'next/head'
import { ContactForm } from '../../components/contents'
export default function Contact() {
  return (
    <>
      <Head>
        <title>contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContactForm />
    </>
  )
}
