export { default as MainVisual } from './MainVisual'
export { default as HeadTitle1 } from './HeadTitle1'
export { default as HeadTitle2 } from './HeadTitle2'
export { default as PostTitle1 } from './PostTitle1'
export { default as PostNote } from './PostNote'
export { default as PostDiary } from './PostDiary'
export { default as ContactForm } from './ContactForm'
export { default as DetailNote } from './DetailNote'
