import Head from 'next/head'
import Link from 'next/link'
import { HeadTitle2, PostDiary } from '../../components/contents'
export default function Diary({ diary }) {
  return (
    <>
      <Head>
        <title>diary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <PostDiary items={diary} />
      </div>
    </>
  )
}

export const getStaticProps = async () => {
  const resDiary = await getDiaryPosts()

  // responseが無ければ404にリダイレクトする
  if (!resDiary) {
    return {
      notFound: true,
    }
  }
  return {
    props: { diary: resDiary.contents || null },
  }
}

const getDiaryPosts = async () => {
  const url = 'https://microblog.microcms.io/api/v1/diary'
  const res = await fetch(url, {
    headers: {
      'X-API-KEY': process.env.API_KEY,
    },
  })
  const resData = res.json()
  return resData
}
